### PR TITLE
08Move 10game 08messages 10to 08a 10JSON 08file 10and 08allow 10for 08custom 10messages

### PR DESCRIPTION
**Pull request by laneatomic**
:boom:

### CODE REVIEW

**Comment by laneatomic** [comment]
I'll squash when ready to merge. Leaving the commits for now.

**Comment by laneatomic** [comment]
I think this is about as tested as we can get it in our channel. Played many games of random, as well as every other mode. I think at this point the only issues we might find are a typo here or there in messages themselves (erroneous single quotes vs double quotes, etc.)

**Comment by nyuszika7h** [comment]
test

**Comment by Vgr255** [comment]
The blue and yellow labels are doing wonders.

**Comment by laneatomic** [comment]
:+1:

**Pull request merged**
