### PR TITLE
abra0's suggestion

### PR DESCRIPTION
**Pull request by acz13**
<+abra0> petition to add "I'm sorry I can't do that Dave" to !ping responses  
I have no idea whether this is the real quote or not.

### CODE REVIEW

**Comment by acz13** [comment]
Wups, just realized I messed up big time :-1: :disappointed:

**Comment by Vgr255** [comment]
Wouldn't it be "I'm sorry, I can't let you do that Dave"?

**Comment by nyuszika7h** [comment]
Apparently the actual quote is "I'm sorry Dave, I'm afraid I can't do that".

**Comment by acz13** [comment]
Isn't that what I have?

On Tue, Oct 13, 2015 at 1:27 AM, nyuszika7h <notifications@github.com>
wrote:

> Apparently the actual quote is "I'm sorry Dave, I'm afraid I can't do
> that".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lykoss/lykos/pull/171#issuecomment-147606857>.
>



-- 
*Albert Cheng Zhang*

**Comment by Vgr255** [comment]
Seems so. I thought there was a "let you do that" in there, but apparently not.

LGTM

**Comment by nyuszika7h** [comment]
Add a period at the end maybe?

**Pull request merged**
