### PR TITLE
Tweak wording for silver bullet messages

### PR DESCRIPTION
**Pull request by ammongit**
The tenses and wording was slightly awkward.

### CODE REVIEW

**Comment by ishanyx** [comment]
this removes the distinction between an accidental headshot and a sharpshooter headshot - is that intentional?

**Comment by skizzerz** [comment]
No, that distinction needs to exist

**Comment by ammongit** [comment]
Alright, will adjust

**Comment by nyuszika7h** [comment]
I think the way it is currently makes sense too, I mean the process of death can take a while, though not too long because the player is immediately removed from the game.

**Pull request closed without merging**
